const dexList = {
  '1inchSwap': 'https://images.swft.pro/dex/1inch.png',
  UniSwapV2: 'https://images.swft.pro/dex/uniswap.png',
  PancakeSwapV2: 'https://images.swft.pro/dex/pancake.png',
  MDexSwap: 'https://images.swft.pro/dex/mdex.png',
  PippiSwap: 'https://images.swft.pro/dex/pippi.png',
  LavaSwap: '',
  SushiSwap: 'https://images.swft.pro/dex/sushi.png',
  DODOSwap: 'https://images.swft.pro/dex/dodo.png',
  O3Swap: 'https://images.swft.pro/dex/o3.png',
  ClassZZ: 'https://images.swft.pro/dex/czz.png',
  BinanceBridge:
    'https://images.swft.pro/inch1/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c.png',
  SWFT: 'https://images.swft.pro/dex/SWFT.png',
  CBridge: 'https://images.swft.pro/dex/cBridge.png',
  Orca: 'https://images.swft.pro/dex/orca.png',
  Axie: 'https://cdn.axieinfinity.com/landing-page/_next/static/images/logo-f3b5c962671a2516bc9fef42ad9e9145@1x.webp',
  Cherryswap: 'https://images.swft.pro/dex/cherryswap.png',
  Spookyswap: 'https://images.swft.pro/dex/spookyswap.png',
  ArbSushiSwap: 'https://images.swft.pro/dex/sushi.png',
  Pangolin: 'https://images.swft.pro/dex/Pangolin.png',
  Traderjoe: 'https://traderjoexyz.com/static/media/logo.bc60f78d.png',
  bridgers1: 'https://images.swft.pro/dex/bridgers1.png',
  bridgers2: 'https://images.swft.pro/dex/bridgers2.png',
  Aggregator: 'https://images.swft.pro/dex/path.png',
  PolygonSushiSwap: 'https://images.swft.pro/dex/sushi.png',
  DogeSwap: 'https://images.swft.pro/dex/dogeswap.png',
  PolygonApeSwap: 'https://images.swft.pro/dex/apeswap.png',
  BscSushiSwap: 'https://images.swft.pro/dex/sushi.png',
  Honeyswap: 'https://images.swft.pro/dex/honeyswap.png',
  QuickSwap: 'https://images.swft.pro/dex/quickswap.png',
  FantomSushiSwap: 'https://images.swft.pro/dex/sushi.png',
  SpiritSwap: 'https://images.swft.pro/dex/spiritswap.png',
  BabySwap: 'https://images.swft.pro/dex/babyswap.png',
  Biswap: 'https://images.swft.pro/dex/biswap.png',
  BscMDexSwap: 'https://images.swft.pro/dex/mdex.png',
  ApeSwap: 'https://images.swft.pro/dex/apeswap.png',
  KSwap: 'https://images.swft.pro/dex/kswap.png',
  MySwap: 'https://images.swft.pro/dex/myswap.png',
  JSwap: 'https://images.swft.pro/dex/jswap.png',
  OkxSushiSwap: 'https://images.swft.pro/dex/sushi.png',
  miningTW: 'https://images.swft.pro/dex/miningTW.png',
}
export default dexList
